export const KNOWN_MUTATION_TRAIT_IDS = {
  acrobatic: 'acrobatic',
  condensationShield: 'condensation_shield',
  deformedBody: 'deformed_body',
  disruptedMagic: 'disrupted_magic',
  ephemeralShield: 'ephemeral_shield',
  evasiveFlight: 'evasive_flight',
  gelatinousBody: 'gelatinous_body',
  icemail: 'icemail',
  icyBlueScales: 'icy_blue_scales',
  iridescentScales: 'iridescent_scales',
  ironFusedScales: 'iron_fused_scales',
  largeBonePlates: 'large_bone_plates',
  moltenScales: 'molten_scales',
  proteanGrace: 'protean_grace',
  reckless: 'reckless',
  reducedAc: 'reduced_ac',
  reducedEv: 'reduced_ev',
  repulsionField: 'repulsion_field',
  ruggedBrownScales: 'rugged_brown_scales',
  sanguineArmour: 'sanguine_armour',
  shaggyFur: 'shaggy_fur',
  sharpScales: 'sharp_scales',
  slimyGreenScales: 'slimy_green_scales',
  stoneBody: 'stone_body',
  sturdyFrame: 'sturdy_frame',
  thinMetallicScales: 'thin_metallic_scales',
  toughSkin: 'tough_skin',
  trickster: 'trickster',
  yellowScales: 'yellow_scales',
} as const

export type KnownMutationTraitId =
  (typeof KNOWN_MUTATION_TRAIT_IDS)[keyof typeof KNOWN_MUTATION_TRAIT_IDS]
