import { describe, expect, it } from 'vitest'
import {
  buildCrawlEquipmentCatalogFromSource,
  deriveUnrandEnumName,
  preprocessCrawlEquipmentSource,
} from '../../src/audit/crawlEquipmentCatalog'

describe('crawlEquipmentCatalog', () => {
  it('filters TAG_MAJOR_VERSION conditions including elif and else branches', () => {
    const source = [
      'always',
      '#if TAG_MAJOR_VERSION == 34',
      'only34',
      '#elif TAG_MAJOR_VERSION > 34',
      'only35plus',
      '#else',
      'fallback',
      '#endif',
    ].join('\n')

    expect(preprocessCrawlEquipmentSource(source, 34)).toContain('only34')
    expect(preprocessCrawlEquipmentSource(source, 34)).not.toContain('only35plus')
    expect(preprocessCrawlEquipmentSource(source, 35)).toContain('only35plus')
    expect(preprocessCrawlEquipmentSource(source, 35)).not.toContain('only34')
  })

  it('builds equipment catalog entries from Crawl source snippets', () => {
    const catalog = buildCrawlEquipmentCatalogFromSource({
      tagMajorVersion: 34,
      itemPropEnum: [
        'enum brand_type',
        '{',
        '    SPWPN_FORBID_BRAND = -1,',
        '    SPWPN_NORMAL,',
        '    SPWPN_FLAMING,',
        '#if TAG_MAJOR_VERSION == 34',
        '    SPWPN_OBSOLETE_TEST,',
        '#endif',
        '    SPWPN_CHAOS,',
        '    NUM_REAL_SPECIAL_WEAPONS,',
        '    SPWPN_ACID,',
        '    NUM_SPECIAL_WEAPONS,',
        '};',
        'enum special_missile_type // comment with { braces }',
        '{',
        '    SPMSL_FORBID_BRAND = -1,',
        '    SPMSL_NORMAL,',
        '    SPMSL_POISONED,',
        '    NUM_REAL_SPECIAL_MISSILES,',
        '    NUM_SPECIAL_MISSILES = NUM_REAL_SPECIAL_MISSILES,',
        '};',
        'enum jewellery_type',
        '{',
        '    RING_PROTECTION,',
        '    RING_FIRST_RING = RING_PROTECTION,',
        '    RING_WILLPOWER,',
        '    NUM_RINGS,',
        '    AMU_ACROBAT = 35,',
        '    AMU_FIRST_AMULET = AMU_ACROBAT,',
        '    AMU_REFLECTION,',
        '    NUM_JEWELLERY',
        '};',
        'enum special_armour_type',
        '{',
        '    SPARM_FORBID_EGO = -1,',
        '    SPARM_NORMAL,',
        '#if TAG_MAJOR_VERSION == 34',
        '    SPARM_RUNNING,',
        '#endif',
        '    SPARM_WILLPOWER,',
        '    NUM_REAL_SPECIAL_ARMOURS,',
        '    NUM_SPECIAL_ARMOURS,',
        '};',
      ].join('\n'),
      itemName: [
        'static const char *weapon_brands_terse[] =',
        '{',
        '    "", "flame",',
        '#if TAG_MAJOR_VERSION == 34',
        '    "obsolete",',
        '#endif',
        '    "chaos", "num_special", "acid",',
        '};',
        'static const char *weapon_brands_verbose[] =',
        '{',
        '    "", "flaming",',
        '#if TAG_MAJOR_VERSION == 34',
        '    "obsolescence",',
        '#endif',
        '    "chaos", "num_special", "acid",',
        '};',
        'static const char *weapon_brands_adj[] =',
        '{',
        '    "", "flaming",',
        '#if TAG_MAJOR_VERSION == 34',
        '    "obsolete",',
        '#endif',
        '    "chaotic", "num_special", "acidic",',
        '};',
        'const char* special_armour_type_name(special_armour_type ego, bool terse)',
        '{',
        '    if (!terse)',
        '    {',
        '        switch (ego)',
        '        {',
        '        case SPARM_RUNNING: return "obsolescence";',
        '        case SPARM_WILLPOWER: return "willpower";',
        '        default: return "bugginess";',
        '        }',
        '    }',
        '    else',
        '    {',
        '        switch (ego)',
        '        {',
        '        case SPARM_RUNNING: return "obsolete";',
        '        case SPARM_WILLPOWER: return "Will+";',
        '        default: return "buggy";',
        '        }',
        '    }',
        '}',
        'const char* armour_ego_name(const item_def& item, bool terse)',
        '{',
        '    return special_armour_type_name(get_armour_ego_type(item), terse);',
        '}',
        'const char* missile_brand_name(const item_def &item, mbn_type t)',
        '{',
        '    switch (brand)',
        '    {',
        '    case SPMSL_POISONED:',
        '        return t == MBN_NAME ? "poisoned" : "poison";',
        '    default:',
        '        return t == MBN_TERSE ? "buggy" : "bugginess";',
        '    }',
        '}',
        'const char* jewellery_effect_name(int jeweltype, bool terse)',
        '{',
        '    if (!terse)',
        '    {',
        '        switch (static_cast<jewellery_type>(jeweltype))',
        '        {',
        '        case RING_PROTECTION: return "protection";',
        '        case RING_WILLPOWER: return "willpower";',
        '        case AMU_ACROBAT: return "the acrobat";',
        '        case AMU_REFLECTION: return "reflection";',
        '        default: return "buggy jewellery";',
        '        }',
        '    }',
        '    else',
        '    {',
        '        switch (static_cast<jewellery_type>(jeweltype))',
        '        {',
        '        case RING_PROTECTION: return "AC";',
        '        case RING_WILLPOWER: return "Will+";',
        '        case AMU_ACROBAT: return "Acrobat";',
        '        case AMU_REFLECTION: return "Reflect";',
        '        default: return "buggy";',
        '        }',
        '    }',
        '}',
      ].join('\n'),
      mapdef: [
        'const char* armour_egos[] =',
        '{',
        '#if TAG_MAJOR_VERSION == 34',
        '    "running",',
        '#endif',
        '    "willpower",',
        '    nullptr',
        '};',
        'const char* weapon_brands[] =',
        '{',
        '    "flaming",',
        '#if TAG_MAJOR_VERSION == 34',
        '    "obsolete_test",',
        '#endif',
        '    "chaos",',
        '    nullptr',
        '};',
        'const char* missile_brands[] =',
        '{',
        '    "poisoned",',
        '    nullptr',
        '};',
      ].join('\n'),
      artData: [
        'NAME:   robe of Augmentation',
        'OBJ:    OBJ_ARMOUR/ARM_ROBE',
        'TYPE:   robe',
        'BOOL:   special',
        '',
        'ENUM:   DUMMY1',
        'NAME:   DUMMY UNRANDART 1',
        'OBJ:    OBJ_UNASSIGNED/250',
      ].join('\n'),
    })

    expect(catalog.armourEgos).toContainEqual({
      enumName: 'SPARM_WILLPOWER',
      token: 'willpower',
      displayName: 'willpower',
      terseName: 'Will+',
      isObsolete: false,
    })
    expect(catalog.weaponBrands.find((brand) => brand.enumName === 'SPWPN_ACID')).toMatchObject({
      displayName: 'acid',
      isItemBrand: false,
    })
    expect(catalog.missileBrands).toEqual([
      {
        enumName: 'SPMSL_POISONED',
        token: 'poisoned',
        displayName: 'poisoned',
        terseName: 'poison',
        isObsolete: false,
      },
    ])
    expect(catalog.jewelleryEffects.find((effect) => effect.enumName === 'RING_WILLPOWER')).toMatchObject({
      itemClass: 'ring',
      displayName: 'willpower',
      terseName: 'Will+',
    })
    expect(catalog.unrandarts).toEqual([
      {
        enumName: 'UNRAND_AUGMENTATION',
        name: 'robe of Augmentation',
        objectClass: 'OBJ_ARMOUR',
        subtype: 'ARM_ROBE',
        displayType: 'robe',
        flags: ['special'],
        isDeleted: false,
        isNoGen: false,
      },
    ])
  })

  it('derives unrand enum names using Crawl art-data rules', () => {
    expect(deriveUnrandEnumName('ring of the Octopus King')).toBe('UNRAND_OCTOPUS_KING')
    expect(deriveUnrandEnumName('demon blade "Leech"')).toBe('UNRAND_LEECH')
    expect(deriveUnrandEnumName("Maxwell's patent armour", 'MAXWELL')).toBe('UNRAND_MAXWELL')
  })
})
